#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# No dependencies

set -eo pipefail

/opt/nginx-ldap-auth/nginx-ldap-auth-daemon.py \
    2>&1 | awk -W interactive '{print "[nginx-ldap-auth-daemon] " $0}'
