#!/usr/bin/with-contenv bash
# shellcheck shell=bash

NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'
YELLOW='\033[1;33m'

# Check to make sure the correct command line arguments have been set
EXITCODE=0

if [ -z "${PROTECTED_BACKEND_HOST}" ]; then
  echo -e "${LIGHTRED}ERROR: PROTECTED_BACKEND_HOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${PROTECTED_BACKEND_PORT}" ]; then
  echo -e "${LIGHTRED}ERROR: PROTECTED_BACKEND_PORT environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${NGINX_SERVER_NAME}" ]; then
  echo -e "${LIGHTRED}ERROR: NGINX_SERVER_NAME environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${NGINX_PATH_SSL_CERTIFICATE}" ]; then
  echo -e "${LIGHTRED}ERROR: NGINX_PATH_SSL_CERTIFICATE environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${NGINX_PATH_SSL_CERTIFICATE_KEY}" ]; then
  echo -e "${LIGHTRED}ERROR: NGINX_PATH_SSL_CERTIFICATE_KEY environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${LDAP_URL}" ]; then
  echo -e "${LIGHTRED}ERROR: LDAP_URL environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${LDAP_BASE_DN}" ]; then
  echo -e "${LIGHTRED}ERROR: LDAP_BASE_DN environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${LDAP_BIND_DN}" ]; then
  echo -e "${LIGHTRED}ERROR: LDAP_BIND_DN environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

if [ -z "${LDAP_BIND_PW}" ]; then
  echo -e "${LIGHTRED}ERROR: LDAP_BIND_PW environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -e "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi

if [ $EXITCODE -ne 0 ]; then
  exit 1
fi
