#!/usr/bin/with-contenv /usr/bin/env bash
# shellcheck shell=bash

NGINX_CACHE_DIR="/opt/nginx/cache"

mkdir -p "$NGINX_CACHE_DIR"
chown -R www-data "$NGINX_CACHE_DIR"

{
echo <<< EOL
user www-data;
error_log /dev/stdout $NGINX_ERROR_LOG_LEVEL;
http {
    access_log /dev/stdout;
    proxy_cache_path $NGINX_CACHE_DIR  keys_zone=auth_cache:10m;
    upstream backend {
        server 127.0.0.1:9000;
    }
    server {
        listen 8081;
        # Protected application
        location / {
            auth_request /auth-proxy;
            error_page 401 =200 /login;
            proxy_pass http://backend/;
        }

        location /login {
            proxy_pass http://backend/login;
            proxy_set_header X-Target \$request_uri;
        }

        location = /auth-proxy {
            internal;
            proxy_pass http://127.0.0.1:8888;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_cache auth_cache;
            proxy_cache_valid 200 10m;
            proxy_cache_key "\$http_authorization\$cookie_nginxauth";
            proxy_set_header X-Ldap-URL      "ldap://example.com";
            #proxy_set_header X-Ldap-Starttls "true";
            proxy_set_header X-Ldap-BaseDN   "cn=Users,dc=test,dc=local";
            proxy_set_header X-Ldap-BindDN   "cn=root,dc=test,dc=local";
            proxy_set_header X-Ldap-BindPass "secret";
            proxy_set_header X-CookieName "nginxauth";
            proxy_set_header Cookie nginxauth=\$cookie_nginxauth;
            #proxy_set_header X-Ldap-Template "(sAMAccountName=%(username)s)";
            #proxy_set_header X-Ldap-DisableReferrals "true";
            #proxy_set_header X-Ldap-Realm    "Restricted";
        }

    }
}
EOL
} > /etc/nginx/nginx.conf
